import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, deleteDoc, collection, getDocs, addDoc, query, orderBy, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js?v=7";

const fbApp=initializeApp(firebaseConfig), auth=getAuth(fbApp), db=getFirestore(fbApp);
const NAMES=["Diego","Sunkar","Silvano","Giuseppe","Vitalin","Davide","Zara","Lisa","Anna","Niko","Raffa","Alex"];
let state={employees:NAMES,kitchenPercent:20,history:[]}, user=null, unsub=null;
const $=id=>document.getElementById(id), euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(+n||0), today=()=>new Date().toISOString().slice(0,10), esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

$('loginBtn').onclick=async()=>{try{$('err').textContent='';await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(e){$('err').textContent='Accesso non riuscito. Controlla email/password o regole Firestore.'}};
$('logoutBtn').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{user=u;if(!u){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}$('login').classList.add('hidden');$('app').classList.remove('hidden');$('who').textContent=u.email;await load();init();chatListen()});

async function load(){const s=await getDoc(doc(db,'restaurants','angies','settings','main'));if(s.exists()){let d=s.data();state.employees=d.employees||NAMES;state.kitchenPercent=d.kitchenPercent??20}else await setDoc(doc(db,'restaurants','angies','settings','main'),{employees:NAMES,kitchenPercent:20});const days=await getDocs(collection(db,'restaurants','angies','days'));state.history=days.docs.map(x=>x.data()).sort((a,b)=>a.date.localeCompare(b.date))}
function init(){$('date').value=today();$('from').value=today().slice(0,8)+'01';$('to').value=today();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab,b));$('saveDay').onclick=saveDay;$('clear').onclick=clear;$('export').onclick=csv;$('deleteAll').onclick=deleteAll;$('saveSettings').onclick=saveSettings;$('send').onclick=sendMsg;['cash','card','from','to'].forEach(id=>$(id).oninput=render);render()}
function tab(id,b){
document.querySelectorAll('.page').forEach(p=>{p.classList.remove('active');p.style.display='none';});
const page=$(id);
if(page){page.classList.add('active');page.style.display='block';}
document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));
if(b)b.classList.add('active');
render();
}
function split(r){let p=state.kitchenPercent/100,c=r.cash||0,ca=r.card||0,t=r.total??c+ca;return{cash:c,card:ca,total:t,salaCash:r.salaCash??c*(1-p),salaCard:r.salaCard??ca*(1-p),cucinaCash:r.cucinaCash??c*p,cucinaCard:r.cucinaCard??ca*p,sala:r.sala??t*(1-p),kitchen:r.kitchen??t*p}}
function data(){let cash=+$('cash').value||0,card=+$('card').value||0,h=[...document.querySelectorAll('.hour')].map(x=>+x.value||0),th=h.reduce((a,b)=>a+b,0),p=state.kitchenPercent/100,salaCash=cash*(1-p),salaCard=card*(1-p),cucinaCash=cash*p,cucinaCard=card*p;return{date:$('date').value,cash,card,h,totalHours:th,total:cash+card,salaCash,salaCard,cucinaCash,cucinaCard,sala:salaCash+salaCard,kitchen:cucinaCash+cucinaCard,cashHour:th?salaCash/th:0,cardHour:th?salaCard/th:0}}
function render(){hours();calc();dash();history();stats();settings()}
function hours(){let html='<tr><th>Dipendente</th><th>Ore</th><th>Cash</th><th>Carta</th><th>Totale</th></tr>';state.employees.forEach((n,i)=>html+=`<tr><td>${esc(n)}</td><td><input class="hour" type="number" step="0.25" min="0"></td><td id="tc${i}" class="cash-col">${euro(0)}</td><td id="tp${i}" class="card-col">${euro(0)}</td><td id="tt${i}">${euro(0)}</td></tr>`);$('hours').innerHTML=html;document.querySelectorAll('.hour').forEach(x=>x.oninput=calc)}
function calc(){let d=data();$('nSalaCash').textContent=euro(d.salaCash);$('nSalaCard').textContent=euro(d.salaCard);$('nCucinaCash').textContent=euro(d.cucinaCash);$('nCucinaCard').textContent=euro(d.cucinaCard);$('nHours').textContent=d.totalHours;$('nHourValue').textContent=euro(d.totalHours?d.sala/d.totalHours:0);state.employees.forEach((_,i)=>{let c=d.h[i]*d.cashHour,ca=d.h[i]*d.cardHour,t=c+ca;if($('tc'+i))$('tc'+i).textContent=euro(c);if($('tp'+i))$('tp'+i).textContent=euro(ca);if($('tt'+i))$('tt'+i).textContent=euro(t)})}
async function saveDay(){let d=data();if(!d.date)return alert('Inserisci la data.');if(d.total<=0)return alert('Inserisci Cash o Carta.');if(d.totalHours<=0)return alert('Inserisci almeno un\'ora.');let tips=state.employees.map((name,i)=>({name,hours:d.h[i],cash:d.h[i]*d.cashHour,card:d.h[i]*d.cardHour,total:d.h[i]*(d.cashHour+d.cardHour)}));let rec={date:d.date,cash:d.cash,card:d.card,total:d.total,sala:d.sala,kitchen:d.kitchen,salaCash:d.salaCash,salaCard:d.salaCard,cucinaCash:d.cucinaCash,cucinaCard:d.cucinaCard,tips,updatedBy:user.email,updatedAt:new Date().toISOString()};let idx=state.history.findIndex(r=>r.date===d.date);if(idx>=0){if(!confirm('Questa data esiste già. Vuoi aggiornarla?'))return;state.history[idx]=rec}else state.history.push(rec);state.history.sort((a,b)=>a.date.localeCompare(b.date));await setDoc(doc(db,'restaurants','angies','days',rec.date),rec);clear(false);render();alert('Giornata salvata nel cloud.')}
function clear(reset=true){if(reset)$('date').value=today();$('cash').value=0;$('card').value=0;document.querySelectorAll('.hour').forEach(x=>x.value='');calc()}
function sum(rows,k){return rows.reduce((s,r)=>s+(split(r)[k]||0),0)}
function dash(){let r=state.history;$('dTotal').textContent=euro(sum(r,'total'));$('dCash').textContent=euro(sum(r,'cash'));$('dCard').textContent=euro(sum(r,'card'));$('dDays').textContent=r.length;$('dSala').textContent=euro(sum(r,'sala'));$('dSalaCash').textContent=euro(sum(r,'salaCash'));$('dSalaCard').textContent=euro(sum(r,'salaCard'));$('dCucina').textContent=euro(sum(r,'kitchen'));$('dCucinaCash').textContent=euro(sum(r,'cucinaCash'));$('dCucinaCard').textContent=euro(sum(r,'cucinaCard'));$('recent').innerHTML='<tr><th>Data</th><th>Cash</th><th>Carta</th><th>Sala Cash</th><th>Sala Carta</th><th>Cucina Cash</th><th>Cucina Carta</th><th>Totale</th></tr>'+[...r].slice(-7).reverse().map(x=>{let s=split(x);return`<tr><td>${fmt(x.date)}</td><td>${euro(s.cash)}</td><td>${euro(s.card)}</td><td>${euro(s.salaCash)}</td><td>${euro(s.salaCard)}</td><td>${euro(s.cucinaCash)}</td><td>${euro(s.cucinaCard)}</td><td>${euro(s.total)}</td></tr>`}).join('')}
function history(){let html='<tr><th>Data</th>';state.employees.forEach(n=>html+=`<th>${esc(n)} Cash</th><th>${esc(n)} Carta</th><th>${esc(n)} Totale</th>`);html+='<th>Sala Cash</th><th>Sala Carta</th><th>Sala Totale</th><th>Cucina Cash</th><th>Cucina Carta</th><th>Cucina Totale</th><th>Totale</th><th></th></tr>';state.history.forEach((r,i)=>{let s=split(r);html+=`<tr><td>${fmt(r.date)}</td>`;state.employees.forEach((_,j)=>{let t=r.tips?.[j]||{};html+=`<td>${t.cash?euro(t.cash):''}</td><td>${t.card?euro(t.card):''}</td><td>${t.total?euro(t.total):''}</td>`});html+=`<td>${euro(s.salaCash)}</td><td>${euro(s.salaCard)}</td><td>${euro(s.sala)}</td><td>${euro(s.cucinaCash)}</td><td>${euro(s.cucinaCard)}</td><td>${euro(s.kitchen)}</td><td>${euro(s.total)}</td><td><button onclick="window.delDay(${i})">X</button></td></tr>`});$('hist').innerHTML=html}
window.delDay=async i=>{if(!confirm('Cancellare questa giornata?'))return;let d=state.history[i].date;state.history.splice(i,1);await deleteDoc(doc(db,'restaurants','angies','days',d));render()};
async function deleteAll(){if(!confirm('Cancellare tutto lo storico?'))return;for(let r of state.history)await deleteDoc(doc(db,'restaurants','angies','days',r.date));state.history=[];render()}
function stats(){let f=$('from').value||'0000-01-01',t=$('to').value||'9999-12-31',rows=state.history.filter(r=>r.date>=f&&r.date<=t);$('sTotal').textContent=euro(sum(rows,'total'));$('sCash').textContent=euro(sum(rows,'cash'));$('sCard').textContent=euro(sum(rows,'card'));$('sSala').textContent=euro(sum(rows,'sala'));$('sSalaCash').textContent=euro(sum(rows,'salaCash'));$('sSalaCard').textContent=euro(sum(rows,'salaCard'));$('sCucina').textContent=euro(sum(rows,'kitchen'));$('sCucinaCash').textContent=euro(sum(rows,'cucinaCash'));$('sCucinaCard').textContent=euro(sum(rows,'cucinaCard'));let data=state.employees.map((name,i)=>{let hours=rows.reduce((s,r)=>s+(r.tips?.[i]?.hours||0),0),cash=rows.reduce((s,r)=>s+(r.tips?.[i]?.cash||0),0),card=rows.reduce((s,r)=>s+(r.tips?.[i]?.card||0),0),total=cash+card,days=rows.filter(r=>(r.tips?.[i]?.hours||0)>0).length;return{name,hours,cash,card,total,days}}).sort((a,b)=>b.total-a.total);$('statTable').innerHTML='<tr><th>Dipendente</th><th>Ore</th><th>Cash</th><th>Carta</th><th>Totale</th><th>Giorni</th><th>Media/giorno</th><th>Media/ora</th><th>Rank</th></tr>'+data.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${x.hours}</td><td>${euro(x.cash)}</td><td>${euro(x.card)}</td><td>${euro(x.total)}</td><td>${x.days}</td><td>${euro(x.days?x.total/x.days:0)}</td><td>${euro(x.hours?x.total/x.hours:0)}</td><td>${i+1}</td></tr>`).join('')}
function settings(){$('kitchen').value=state.kitchenPercent;$('emps').innerHTML='<tr><th>N.</th><th>Nome</th></tr>'+state.employees.map((n,i)=>`<tr><td>${i+1}</td><td><input class="emp" value="${esc(n)}"></td></tr>`).join('')}
async function saveSettings(){state.kitchenPercent=+$('kitchen').value||20;state.employees=[...document.querySelectorAll('.emp')].map(x=>x.value.trim()).filter(Boolean);await setDoc(doc(db,'restaurants','angies','settings','main'),{employees:state.employees,kitchenPercent:state.kitchenPercent,updatedBy:user.email,updatedAt:new Date().toISOString()});render();alert('Impostazioni salvate.')}
function chatListen(){if(unsub)unsub();let q=query(collection(db,'restaurants','angies','chat'),orderBy('createdAt','asc'));unsub=onSnapshot(q,snap=>{let box=$('chatBox');box.innerHTML='';snap.forEach(d=>{let m=d.data(),me=m.email===user.email,dt=m.createdAt?.toDate?m.createdAt.toDate().toLocaleString('it-IT'):'';box.innerHTML+=`<div class="msgrow ${me?'me':''}"><strong>${esc(m.name||m.email)}</strong>${esc(m.text)}<br><small>${dt}</small></div>`});box.scrollTop=box.scrollHeight})}
async function sendMsg(){let text=$('msg').value.trim();if(!text)return;await addDoc(collection(db,'restaurants','angies','chat'),{text,email:user.email,name:user.email.split('@')[0],createdAt:serverTimestamp()});$('msg').value=''}
function csv(){let h=['Data'];state.employees.forEach(n=>h.push(`${n} Cash`,`${n} Carta`,`${n} Totale`));h.push('Sala Cash','Sala Carta','Sala Totale','Cucina Cash','Cucina Carta','Cucina Totale','Totale');let lines=[h.join(';')];state.history.forEach(r=>{let s=split(r),row=[fmt(r.date)];state.employees.forEach((_,i)=>row.push(num(r.tips?.[i]?.cash),num(r.tips?.[i]?.card),num(r.tips?.[i]?.total)));row.push(num(s.salaCash),num(s.salaCard),num(s.sala),num(s.cucinaCash),num(s.cucinaCard),num(s.kitchen),num(s.total));lines.push(row.join(';'))});let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='angies_mance.csv';a.click()}
function num(n){return(+n||0).toFixed(2).replace('.',',')}function fmt(d){return new Date(d+'T00:00:00').toLocaleDateString('it-IT')}
